// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by aws-amplify-serverless-plugin/1.3.0 on 2019-01-23T18:17:30.942Z

const awsmobile = {
    aws_cloud_logic_custom: [
        {
            endpoint: 'https://inxjhamw6l.execute-api.eu-west-1.amazonaws.com/dev',
            name: 'ApiGatewayRestApi',
            region: 'eu-west-1'
        }
    ],
    aws_cognito_identity_pool_id: 'eu-west-1:e21586f8-b215-4c81-bd50-720e58a9220d',
    aws_cognito_region: 'eu-west-1',
    aws_project_region: 'eu-west-1',
    aws_user_pools_id: 'eu-west-1_NGA417ZMn',
    aws_user_pools_web_client_id: '6j8pmep41tdlj531ebqigp5gsc'
};

export default awsmobile;
